yys_bio_django/shiki/urls.py
from django.urls import path

from . import views

app_name = "shiki"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>", views.DetailView.as_view(), name="detail"),
    path('search', views.search, name='search'),
]

yys_bio_django/yys_bio_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("shiki/", include("shiki.urls")),
]

yys_bio_django/shiki/models.py
from django.db import models
from django.utils.html import mark_safe


class Role(models.Model):
    name = models.CharField(max_length=200)
    icon = models.ImageField(blank=True)

    def __str__(self):
        return self.name

    def icon_image(self):
        return mark_safe('<img src=%s style="background-color:red;"/>' % self.icon.url)


class Lane(models.Model):
    name = models.CharField(max_length=200)
    icon = models.ImageField(blank=True)

    def __str__(self):
        return self.name


class Shiki(models.Model):
    name = models.CharField(max_length=200)
    GENDER = [
        ("male", "Male"),
        ("female", "Female"),
    ]
    gender = models.CharField(choices=GENDER, max_length=100)
    avatar = models.ImageField(blank=True)
    role_ids = models.ManyToManyField(Role, blank=True)
    lane_ids = models.ManyToManyField(Lane, blank=True)
    fav_point = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def get_roles(self):
        return "\n".join([r.name for r in self.role_ids.all()])

    def get_lanes(self):
        return "\n".join([lane.name for lane in self.lane_ids.all()])

    def avatar_image(self):
        return mark_safe('<img src=%s />' % self.avatar.url)
    avatar_image.short_description = "Avatar"

yys_bio_django/shiki/views.py
from django.shortcuts import render
from django.views import generic
from django.db.models import Q

from .models import Shiki


class IndexView(generic.ListView):
    template_name = "shiki/index.html"
    context_object_name = "most_favorite_shiki"

    def get_queryset(self):
        return Shiki.objects.all().order_by("-fav_point")


class DetailView(generic.DetailView):
    model = Shiki
    template_name = "shiki/detail.html"


def search(request):
    template = "shiki/index.html"

    query = request.GET.get('q')

    result = Shiki.objects.filter(Q(name__icontains=query))
    context = {'shikis': result}
    return render(request, template, context)

yys_bio_django/shiki/templates/shiki/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">
    {% if title %}
    <title>YYS - {{title}}</title>
    {% else %}
    <title>YYS Bio</title>
    {% endif %}

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand font-weight-bold" href="{% url 'shiki:index' %}"><i class="fas fa-file"></i> YYS Bio</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'shiki:index' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
            </li>


        </ul>
        <!------{{ request.get_host }}/blog/search/-->
        <form id="searchform" action="{% url 'shiki:search' %}" method="get">
            <input type="text" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search Here..."/>
            <button type="button" onclick="searchform.submit()" class=" text-white my-color btn-primary"><i
                    class="fa fa-search"></i></button>
        </form>

        <a href="{% url 'shiki:index' %}" class="btn text-white m-2"><i class="fas fa-user-shield"></i> Shiki</a>

    </div>
</nav>
<div class="container my-bg">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}

    {% endblock %}
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

yys_bio_django/shiki/templates/shiki/detail.html
{% extends "shiki/base.html" %}
{% block content %}
<legend>
    <img src="{{ shiki.avatar.url }}">
    <h1>{{ shiki.name }}</h1>
</legend>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<b>Roles</b>
{% for role in shiki.role_ids.all %}
    <img src="{{ role.icon.url }}" style="background-color: red">
{% endfor %}
</br>
<b>Lanes</b>
{% for lane in shiki.lane_ids.all %}
    {{ lane }}<br/>
{% endfor %}
{% endblock content %}

yys_bio_django/shiki/templates/shiki/index.html
{% extends "shiki/base.html" %}
{% block content %}
    {% if most_favorite_shiki %}
    <ul>
        {% for shiki in most_favorite_shiki %}
        <li><a href="{% url 'shiki:detail' shiki.id %}">{{ shiki.name }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No shiki are available.</p>
    {% endif %}
{% endblock content %}